<?php
return [
    'welcome' => 'Welcome',
    'home_title' => 'Home Page',
    'account' => 'Account',
    'settings' => 'Settings',
    'logout' => 'Log Out',
    'login' => 'Log in',
    'create_profile' => 'Create Profile',
    'about' => 'About',
    'dashboard' => 'Dashboard',
    'features' => 'Features',
    'skills' => 'Skills',
    'school' => 'School',
    'language' => 'English',
    'free' => 'is absolutely free, try it now!',
    'read_more' => 'Read more',
    'immersive' => 'Immersive learning experience',
    'personalized_1' => 'is personalized learning. With a comprehensive K-12 curriculum, individualized guidance, and real-time analytics,',
    'personalized_2' => 'meets the unique needs of each learner.',
    'get_started' => 'Get started',
    'learn_more' => 'Learn more',
];