<?php
return [
    'welcome' => 'Добро пожаловать',
    'home_title' => 'Главная страница',
    'account' => 'Аккаунт',
    'settings' => 'Настройки',
    'logout' => 'Выйти',
    'login' => 'Войти',
    'create_profile' => 'Создать профиль',
    'about' => 'О нас',
    'dashboard' => 'Панель управления',
    'features' => 'Функции',
    'skills' => 'Навыки',
    'school' => 'Школа',
    'language' => 'Русский',
    'free' => 'is absolutely free, try it now!',
    'read_more' => 'Read more',
    'immersive' => 'Immersive learning experience',
    'personalized_1' => 'is personalized learning. With a comprehensive K-12 curriculum, individualized guidance, and real-time analytics,',
    'personalized_2' => 'meets the unique needs of each learner.',
    'get_started' => 'Get started',
    'learn_more' => 'Learn more',
    'teacher_reg' => 'Создать аккаунт учителя',
    'teacher_login' => 'Войти',
    'fname' => 'Имя',
    'lname' => 'Фамилия',
    'email' => 'Электронная почта',
    'password' => 'Пароль',
    'treg' => 'Зарегистрироваться',
    'tlogin' => 'Войти в аккаунт учителя',
    'invalidep' => 'Неверный адрес электронной почты или пароль.',
    'lsuccess' => 'Вы успешно вошли',
    'require' => 'Требуется адрес электронной почты и пароль.',
    'allfie' => 'Заполните все поля.',
    'email_already' => 'Уже есть аккаунт с такой почтой',
];